SYSTEM_DATA = {
    "timestamp": "2026-06-16T14:32:17.482Z",
    "hostname": "prod-server-01",
    "uptime_seconds": 2592000,  # 30 days
    "cpu": {
        "usage_percent": 42.7,
        "cores": 16,
        "load_average": {"1min": 3.2, "5min": 2.8, "15min": 2.5},
        "temperature_celsius": 58.3,
        "per_core": [
            35.2,
            48.1,
            22.7,
            67.3,
            31.0,
            44.5,
            55.8,
            29.4,
            38.6,
            52.1,
            27.3,
            41.9,
            60.2,
            33.7,
            45.0,
            39.8,
        ],
    },
    "memory": {
        "total_gb": 64.0,
        "used_gb": 38.5,
        "free_gb": 12.3,
        "cached_gb": 13.2,
        "usage_percent": 60.2,
        "swap": {"total_gb": 8.0, "used_gb": 1.2, "free_gb": 6.8},
    },
    "disk": [
        {
            "mount": "/",
            "device": "/dev/sda1",
            "total_gb": 500,
            "used_gb": 342,
            "free_gb": 158,
            "usage_percent": 68.4,
        },
        {
            "mount": "/data",
            "device": "/dev/sdb1",
            "total_gb": 2000,
            "used_gb": 1523,
            "free_gb": 477,
            "usage_percent": 76.2,
        },
        {
            "mount": "/backup",
            "device": "/dev/sdc1",
            "total_gb": 4000,
            "used_gb": 2890,
            "free_gb": 1110,
            "usage_percent": 72.3,
        },
    ],
    "network": {
        "interfaces": {
            "eth0": {
                "rx_bytes": 48392018402,
                "tx_bytes": 21938472019,
                "rx_errors": 0,
                "tx_errors": 3,
                "speed_mbps": 10000,
            },
            "eth1": {
                "rx_bytes": 12045738291,
                "tx_bytes": 8927364521,
                "rx_errors": 0,
                "tx_errors": 0,
                "speed_mbps": 1000,
            },
        },
        "connections_established": 847,
        "connections_time_wait": 312,
    },
    "processes": {
        "total": 412,
        "running": 3,
        "sleeping": 398,
        "zombie": 1,
        "stopped": 10,
        "top_cpu": [
            {
                "pid": 28912,
                "name": "python3",
                "cpu_percent": 24.5,
                "memory_percent": 12.3,
            },
            {
                "pid": 15483,
                "name": "postgres",
                "cpu_percent": 8.2,
                "memory_percent": 18.7,
            },
            {"pid": 30147, "name": "nginx", "cpu_percent": 3.1, "memory_percent": 2.9},
        ],
    },
    "containers": [
        {
            "name": "web-app",
            "image": "nginx:1.25",
            "status": "running",
            "cpu_percent": 5.2,
            "memory_mb": 512,
        },
        {
            "name": "api-backend",
            "image": "python:3.12-slim",
            "status": "running",
            "cpu_percent": 28.7,
            "memory_mb": 2048,
        },
        {
            "name": "postgres-db",
            "image": "postgres:16",
            "status": "running",
            "cpu_percent": 12.3,
            "memory_mb": 8192,
        },
        {
            "name": "redis-cache",
            "image": "redis:7-alpine",
            "status": "running",
            "cpu_percent": 1.8,
            "memory_mb": 256,
        },
    ],
    "alerts": [
        {
            "severity": "warning",
            "message": "Disk /data usage above 75%",
            "source": "disk_monitor",
        },
        {
            "severity": "critical",
            "message": "1 zombie process detected",
            "source": "process_monitor",
        },
        {
            "severity": "info",
            "message": "CPU temperature elevated (58.3°C)",
            "source": "hw_monitor",
        },
    ],
}
